apiVersion: apps/v1
kind: Deployment
metadata:
  name: rundeck
spec:
  selector:
    matchLabels:
      app: rundeck
  template:
    metadata:
      labels:
        app: rundeck
    spec:
      volumes:
        - name: rundeck-volume
          hostPath:
            path: /opt/rdconf
      containers:
      - name: rd
        # Replace with docker pull rundeckpro/enterprise
        image: rundeck/rundeck:4.2.1
        ports:
        - name: http
          containerPort: 4440
          protocol: TCP
        - name: https
          containerPort: 4443
          protocol: TCP
        env:
        - name: RUNDECK_GRAILS_URL
          value: 'http://localhost:30000'
        volumeMounts:
          - mountPath: /test
            name: rundeck-volume