apiVersion: v1
kind: Service
metadata:
  name: rundeck
spec:
  ports:
  - name: http
    protocol: "TCP"
    port: 4440
    nodePort: 30000 #4440
  - name: https
    protocol: "TCP"
    port: 4443
    nodePort: 30003 #4443
  selector:
    app: rundeck
  type: NodePort